//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public int PartyId { get; set; }
        public string Message_ { get; set; }
        public string Party_Type_ { get; set; }
        public string Address_ { get; set; }
        public int LocationID { get; set; }
    
        public virtual PLocation PLocation { get; set; }
    }
}
